CC = gcc

make_api:
	# $(CC) hw2.c -o hw2 -lpthread
	# $(CC) hw2_checker.c -o hw2_checker -lpthread
	$(CC) hw3_checker.c -o hw3_checker -lpthread
	$(CC) hw3_tester.c -o hw3_tester -lpthread
	# $(CC) hw3_thread.c -o hw3_thread -lpthread
	# $(CC) -o server server.c sockop.c $(CFLAGS)